import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/Theme-Provider";
import { ModeToggle } from "./components/ModeToggle";
import { FaGithub } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="border-b border-gray-300 p-5 flex justify-between items-center">
            <h1 className="text-2xl font-bold">Andy Banh</h1>

            <div className="flex items-center gap-4">
              <a
                href="https://github.com/AndyyBanh"
                aria-label="Github"
                
              >
                <FaGithub size={24}/>
              </a>

              <a 
                href="https://www.linkedin.com/in/andy-banh-a643a0278/"
                aria-label="Linkedin"
              >
                <FaLinkedin size={24}/>
              </a>
              <ModeToggle />
            </div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
